kind: Deployment
apiVersion: apps/v1
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-app
  template:
    metadata:
      labels:
        app: ollama-app
    spec:
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-storage
      containers:
        - resources:
            limits:
              cpu: '32'
              memory: 32Gi
            requests:
              cpu: '2'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - "/bin/ollama pull mistral && /bin/ollama pull llama3 && /bin/ollama pull sroecker/granite-7b-lab"
          name: ollama
          env:
            - name: FOO
              value: BAR
          ports:
            - name: frontend
              containerPort: 11434
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /.ollama
            name: ollama-storage
          terminationMessagePolicy: File
          image: 'docker.io/ollama/ollama:latest'
          args:
            - serve
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
