kind: Deployment
apiVersion: apps/v1
metadata:
  name: rag-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: rag-frontend
          image: 'quay.io/mdargatz/streamlitbot:latest'
          ports:
            - containerPort: 8501
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rag-frontend-config  # Mount the ConfigMap here
          volumeMounts:
            - name: streamlit-localdata
              mountPath: /opt/app-root/src/.cache/
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: streamlit-localdata
          persistentVolumeClaim:
            claimName: rag-frontend-pvc